[mgr]
ratio = [ 1, 2, 3 ]

[opener]
edit = [
	{ run = "${EDITOR:-vi} %s", desc = "$EDITOR",      for = "unix",    block = true },
	{ run = "code %s",          desc = "code",         for = "windows", orphan = true },
	{ run = "code -w %s",       desc = "code (block)", for = "windows", block = true },
]
open = [
	{ run = "xdg-open %s1",    desc = "Open", for = "linux" },
	{ run = "open %s",         desc = "Open", for = "macos" },
	{ run = 'start "" %s1',    desc = "Open", for = "windows", orphan = true },
]
reveal = [
	{ run = "xdg-open %d1",         desc = "Reveal",    for = "linux" },
	{ run = "open -R %s1",          desc = "Reveal",    for = "macos" },
	{ run = "explorer /select,%s1", desc = "Reveal",    for = "windows", orphan = true },
	{ run = "clear; exiftool %s1; echo 'Press enter to exit'; read _", desc = "Show EXIF", for = "unix", block = true },
]
extract = [
	{ run = "unar %s1", desc = "Extract here", for = "unix" },
	{ run = "unar %s1", desc = "Extract here", for = "windows" },
]
play = [
	{ run = "mpv %s",  desc = "Play", orphan = true, for = "unix" },
	{ run = "mpv %s1", desc = "Play", orphan = true, for = "windows" },
	{ run = "mediainfo %s1; echo 'Press enter to exit'; read _", block = true, desc = "Show media info", for = "unix" },
]
download = [
	{ run = "ya emit download --open %S", desc = "Download and open" },
	{ run = "ya emit download %S",        desc = "Download" },
]

[tasks]
bizarre_retry = 5

[confirm]
trash_title   = "Move {n} selected file{s} to trash? (y/N)"
trash_origin  = "top-center"
trash_offset  = [ 0, 2, 50, 3 ]

delete_title  = "Delete {n} selected file{s} permanently? (y/N)"
delete_origin = "top-center"
delete_offset = [ 0, 2, 50, 3 ]

overwrite_title  = "Overwrite an existing file? (y/N)"
overwrite_origin = "top-center"
overwrite_offset = [ 0, 2, 50, 3 ]

quit_title  = "{n} task{s} running, sure to quit? (y/N)"
quit_origin = "top-center"
quit_offset = [ 0, 2, 50, 3 ]
