#!/bin/bash

IFS='\n' read -r -d '' forceadds <<-EOF
    .bash_completion
    .bash_logout
    .bash_profile
    .bashrc
    .bashrc.d/
    .config/dunst/dunstrc
    .config/dunst/dunstrc.d_*
    .config/gtk-2.0/
    .config/gtk-3.0/
    .config/nvim/autoload/
    .config/nvim/init.vim
    .config/pip/
    .config/pulse/daemon.conf
    .config/ranger/
    .config/picom.conf
    .config/sway/
    .config/remmina
    .config/user-dirs.dirs
    .editorconfig
    .gitconfig
    .gitignore.d/dot*
    .i3/
    .local/etc
    .local/share/applications/
    .local/share/bash-completion
    .local/share/doc/
    .local/share/icons/
    .local/man/
    .local/share/nautilus/
    .local/share/nemo/
    .pam_environment
    .pastebinit.xml
    .profile
    .screenlayout
    .screenrc
    .selected_editor
    bin/
EOF

cd $HOME
for entry in ${forceadds}
do
    vcsh run dot git add --force ${entry} ||:
done

IFS='\n' read -r -d '' forceremoves <<-EOF
EOF
 
cd $HOME
for entry in ${forceremoves}
do
    vcsh run dot git rm -r --cached --quiet ${entry} ||:
done

