[general]
fullscreen = false
early-exit = true
corner-roundness = 10
# possible values: pointer, crop, line, arrow, rectangle, text, marker, blur, brush
initial-tool = "highlight"
copy-command = "wl-copy"
annotation-size-factor = 0.5
action-on-enter = "save-to-clipboard"
save-after-copy = true
right-click-copy = true
default-hide-toolbars = false
primary-highlighter = "block"
disable-notifications = true


# Font to use for text annotations
[font]
family = "Roboto"
style = "Bold"

# Custom colours for the colour palette
[color-palette]
# These will be shown in the toolbar for quick selection
palette = [
    "#fff400",
    "#ff2d20",
    "#0012ff",
]

# These will be available in the color picker as presets
# Leave empty to use GTK's default
custom = [
]
