# https://github.com/gabm/Satty/blob/main/README.md#configuration-file

[general]
actions-on-enter = ["save-to-clipboard", "save-to-file", "exit"]
actions-on-right-click = ["save-to-clipboard", "save-to-file", "exit"]
actions-on-escape = ["save-to-clipboard", "save-to-file", "exit"]
annotation-size-factor = 0.5
brush-smooth-history-size = 10
copy-command = "wl-copy"
corner-roundness = 20
default-hide-toolbars = false
disable-notifications = true
early-exit = true
fullscreen = false
# possible values: pointer, crop, line, arrow, rectangle, text, marker, blur, brush
initial-tool = "highlight"
primary-highlighter = "block"
right-click-copy = true
save-after-copy = true


# Font to use for text annotations
[font]
family = "Roboto"
style = "Bold"


# Custom colours for the colour palette
[color-palette]
# These will be shown in the toolbar for quick selection
palette = [
    "#fffB00",
    "#EE540C",
    "#ff2d20",
    "#189222",
    "#0012ff",
]

# These will be available in the color picker as presets
# Leave empty to use GTK's default
custom = [
]
