function! custom_init#before() abort

    set mouse=r

    " endable/disable pastemode in insert mode
    set pastetoggle=<F2>

    " disable folding
    set nofoldenable

    " enable/disable linenumbers in normal mode
    map <silent> <F2> :set invnumber<cr>

    " F7 in command mode removes trailing whitespace
    :nnoremap <silent> <F7> :let _s=@/<Bar>:%s/\s\+$//e<Bar>:let @/=_s<Bar>:nohl<CR>

    " Tagbar
    nmap <F8> :TagbarToggle<CR>

    " underline cursorline
    highlight CursorLine gui=underline cterm=underline

    " toggle wrapping
    "function ToggleWrap()
    " if (&wrap == 1)
    "   set nowrap
    " else
    "   set wrap
    " endif
    "endfunction
    "map <F9> :call ToggleWrap()<CR>
    "map! <F9> ^[:call ToggleWrap()<CR>

    " generated by alacritty-colorscheme
    source ~/.vimrc_background

    " https://spacevim.org/layers/lang/python/
    let g:neoformat_python_black = {
        \ 'exe': 'black',
        \ 'stdin': 1,
        \ 'args': ['-q', '-'],
        \ }
    let g:neoformat_enabled_python = ['black']

    set statusline+=%#warningmsg#
    set statusline+=%{SyntasticStatuslineFlag()}
    set statusline+=%*

    let g:syntastic_always_populate_loc_list = 1
    let g:syntastic_auto_loc_list = 1
    let g:syntastic_check_on_open = 1
    let g:syntastic_check_on_wq = 0
endf


function! custom_init#after() abort

    " Fix auto-indentation for YAML files
    au! BufNewFile,BufReadPost *.{yaml,yml} set filetype=yaml foldmethod=indent
    autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab indentkeys-=0# indentkeys-=<:>

endf



